"use client";

import { getReportDashboardUrl } from "@/lib/api";

export default function ReportsPage() {
  const dashboardUrl = getReportDashboardUrl();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-white">XSLT Reports</h1>
        <p className="mt-1 text-slate-400">
          HTML dashboard generated by transforming library.xml with report.xslt on the backend
        </p>
      </div>

      <div className="flex gap-3">
        <a
          href={dashboardUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="rounded-lg bg-sky-500 px-5 py-2.5 text-sm font-semibold text-white hover:bg-sky-400"
        >
          Open Dashboard in New Tab
        </a>
      </div>

      <div className="overflow-hidden rounded-xl border border-slate-800">
        <iframe
          src={dashboardUrl}
          title="XSLT Library Dashboard"
          className="h-[800px] w-full bg-white"
        />
      </div>
    </div>
  );
}
